# General settings
title: Randy Deng
author: Randy Deng
email: randy@randydeng.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm always looking to work on new and exciting projects. Need something built? Or just want to chat? Leave me a message and I'll get back to you as soon as I can.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.randydeng.com" # the base hostname & protocol for your site, e.g. http://example.com

# Social Media
linkedin_username: randydeng
github_username: randydeng
rss: subscribe

# Header pages
header_pages:
  - work.md
  - blog.md
  - resume.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
disqus:
  shortname: randydeng
  
# Blog
show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
